concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "docker-runner"
  url = "http://dev.sample.local:8929/"
  id = 2
  token = "glrt-abcdefghijklmnopqrst"
  token_obtained_at = 2023-10-17T18:11:17Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    Insecure = false
  [runners.docker]
    tls_verify = false
    image = "container-dev-all-in-one-dood:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    shm_size = 0
    extra_hosts = ['dev.sample.local:192.168.0.65']
    pull_policy = "if-not-present"
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
